"""sync_models_to_db

迁移版本：53d6bc8de618
前置版本：0001
创建时间：2026-03-04 17:35:22.494815+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53d6bc8de618'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('customer_id', sa.UUID(), nullable=True, comment='指定客户；NULL = 通用券（任何人可用）'))
    op.add_column('coupons', sa.Column('referral_id', sa.UUID(), nullable=True, comment='来源转介绍记录（若为转介绍奖励）'))
    op.add_column('coupons', sa.Column('min_purchase_fen', sa.Integer(), server_default='0', nullable=False, comment='最低消费门槛（分）；0 = 无门槛'))
    op.add_column('coupons', sa.Column('is_used', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('coupons', sa.Column('used_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('coupons', sa.Column('used_on_package_id', sa.UUID(), nullable=True, comment='使用在哪个课包上'))
    op.alter_column('coupons', 'code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               comment='优惠券唯一码，如 "REF-ABCD"',
               existing_comment='优惠券码（唯一）',
               existing_nullable=False)
    op.alter_column('coupons', 'discount_type',
               existing_type=sa.VARCHAR(length=20),
               comment='fixed_fen（固定减免分）| percentage_bps（百分比基点）',
               existing_comment='fixed_fen | percentage_bps',
               existing_nullable=False)
    op.alter_column('coupons', 'discount_value',
               existing_type=sa.INTEGER(),
               comment='折扣值（配合 discount_type 解读）',
               existing_nullable=False)
    op.drop_index('ix_coupons_code', table_name='coupons')
    op.create_foreign_key(None, 'coupons', 'users', ['customer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'coupons', 'referrals', ['referral_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'coupons', 'customer_packages', ['used_on_package_id'], ['id'], ondelete='SET NULL')
    op.create_table_comment(
        'coupons',
        '优惠券，支持转介绍奖励和手动发放',
        existing_comment='优惠券',
        schema=None
    )
    op.drop_column('coupons', 'max_discount_fen')
    op.drop_column('coupons', 'is_active')
    op.drop_column('coupons', 'usage_limit')
    op.drop_column('coupons', 'usage_count')
    op.drop_column('coupons', 'min_order_fen')
    op.add_column('courses', sa.Column('course_type', sa.String(length=50), nullable=False, comment='package（套餐）| single（单次）| trial（体验课）'))
    op.add_column('courses', sa.Column('session_count', sa.Integer(), nullable=False, comment='总课时数'))
    op.add_column('courses', sa.Column('cost_per_session_fen', sa.Integer(), nullable=True, comment='单课时成本（分）= price_fen / session_count，冗余字段便于查询'))
    op.add_column('courses', sa.Column('promo_price_fen', sa.Integer(), nullable=True, comment='促销价（分）；NULL 表示无促销'))
    op.add_column('courses', sa.Column('promo_start_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('courses', sa.Column('promo_end_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('courses', sa.Column('sop_template_id', sa.UUID(), nullable=True, comment='Phase 2: 关联 AI SOP 治疗方案模板'))
    op.alter_column('courses', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='课程名称，如 "肩颈调理套餐 10次"',
               existing_comment='课程名称',
               existing_nullable=False)
    op.alter_column('courses', 'validity_days',
               existing_type=sa.INTEGER(),
               comment='有效天数；NULL 表示不限期',
               existing_comment='有效期（天）；NULL 表示永不过期',
               existing_nullable=True)
    op.alter_column('courses', 'price_fen',
               existing_type=sa.INTEGER(),
               comment='定价（分）',
               existing_comment='标准售价（分）',
               existing_nullable=False)
    op.alter_column('courses', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='FALSE = 下架；客户端不展示，但已购课包不受影响',
               existing_comment='FALSE 时不在前端展示',
               existing_nullable=False)
    op.alter_column('courses', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               nullable=False,
               comment='扩展元数据（JSON）',
               existing_comment='扩展属性（Phase 2）')
    op.drop_index('ix_courses_category', table_name='courses')
    op.drop_index('ix_courses_is_active', table_name='courses')
    op.create_table_comment(
        'courses',
        '课程目录，定义套餐/单次课的规格和价格',
        existing_comment='课程 / 服务项目定义',
        schema=None
    )
    op.drop_column('courses', 'sessions_included')
    op.drop_column('courses', 'category')
    op.add_column('customer_packages', sa.Column('referral_id', sa.UUID(), nullable=True, comment='关联转介绍记录（若通过转介绍购买）'))
    op.add_column('customer_packages', sa.Column('purchase_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False, comment='购买日期'))
    op.add_column('customer_packages', sa.Column('agreed_price_fen', sa.Integer(), nullable=False, comment='实际成交价（分），可能低于定价'))
    op.add_column('customer_packages', sa.Column('amount_paid_fen', sa.Integer(), server_default='0', nullable=False, comment='已实收金额（分）'))
    op.add_column('customer_packages', sa.Column('sold_by_commission_fen', sa.Integer(), nullable=True, comment='销售佣金（分），付款确认后计算'))
    op.alter_column('customer_packages', 'customer_id',
               existing_type=sa.UUID(),
               comment='购买客户',
               existing_nullable=False)
    op.alter_column('customer_packages', 'course_id',
               existing_type=sa.UUID(),
               comment='购买的课程模板',
               existing_nullable=False)
    op.alter_column('customer_packages', 'sold_by_staff_id',
               existing_type=sa.UUID(),
               comment='销售该课包的技师。Phase 1: 同时决定服务技师（SessionRecord.therapist_id 须等于此值）。Phase 2: 独立于治疗方案指定的技师。',
               existing_comment='销售技师；Phase 1：therapist_id 必须等于此值（应用层校验）',
               existing_nullable=True)
    op.alter_column('customer_packages', 'expiry_date',
               existing_type=sa.DATE(),
               comment='到期日期（由 validity_days 计算）；NULL = 不限期',
               existing_comment='到期日；NULL 永不过期',
               existing_nullable=True)
    op.alter_column('customer_packages', 'sessions_total',
               existing_type=sa.INTEGER(),
               comment='总课时数（从 Course.session_count 复制）',
               existing_comment='购买课次数',
               existing_nullable=False)
    op.alter_column('customer_packages', 'sessions_used',
               existing_type=sa.INTEGER(),
               comment='已消耗课时（每次销课 +1，受 CHECK 约束）',
               existing_comment='已完成课次数（行锁保护，防并发错误）',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('customer_packages', 'sessions_gifted',
               existing_type=sa.INTEGER(),
               comment='转介绍奖励赠送课时',
               existing_comment='赠送课次数',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('customer_packages', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='pending | partial | paid | refunded',
               existing_comment='pending | paid | refunded | partial_refunded',
               existing_nullable=False)
    op.drop_index('ix_customer_packages_expiry', table_name='customer_packages')
    op.create_index('ix_customer_packages_expiry', 'customer_packages', ['expiry_date'], unique=False)
    op.drop_constraint('fk_customer_packages_coupon_id', 'customer_packages', type_='foreignkey')
    op.drop_constraint('fk_customer_packages_sold_by_staff_id', 'customer_packages', type_='foreignkey')
    op.create_foreign_key(None, 'customer_packages', 'users', ['sold_by_staff_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'customer_packages', 'referrals', ['referral_id'], ['id'], ondelete='SET NULL')
    op.create_table_comment(
        'customer_packages',
        '客户课包，追踪购买和课时消耗',
        existing_comment='客户课包（购买记录）',
        schema=None
    )
    op.drop_column('customer_packages', 'price_paid_fen')
    op.drop_column('customer_packages', 'coupon_id')
    op.alter_column('notification_logs', 'triggered_by_id',
               existing_type=sa.UUID(),
               comment='触发此通知的管理员；NULL = 系统自动触发',
               existing_nullable=True)
    op.alter_column('notification_logs', 'template_id',
               existing_type=sa.VARCHAR(length=100),
               comment='微信订阅消息模板 ID',
               existing_nullable=False)
    op.alter_column('notification_logs', 'channel',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='subscribe_message | sms（Phase 2）| email（Phase 2）',
               existing_nullable=False)
    op.alter_column('notification_logs', 'content_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='发送时的完整消息体快照（审计留存）',
               existing_nullable=False)
    op.alter_column('notification_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_comment='pending | sent | failed',
               existing_nullable=False)
    op.alter_column('notification_logs', 'wx_msg_id',
               existing_type=sa.VARCHAR(length=100),
               comment='微信返回的消息 ID',
               existing_nullable=True)
    op.alter_column('notification_logs', 'trigger_type',
               existing_type=sa.VARCHAR(length=50),
               comment='manual_blast | session_reminder | package_expiry | referral_reward | promotion',
               existing_nullable=False)
    op.alter_column('referrals', 'referrer_id',
               existing_type=sa.UUID(),
               comment='推荐人（老客户）',
               existing_nullable=False)
    op.alter_column('referrals', 'referee_id',
               existing_type=sa.UUID(),
               comment='被推荐人（新客户），每人只能被推荐一次',
               existing_nullable=False)
    op.alter_column('referrals', 'reward_type',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_comment='gift_session | coupon | cash',
               existing_nullable=False)
    op.alter_column('referrals', 'reward_value',
               existing_type=sa.INTEGER(),
               comment='奖励值：课时数（gift_session）或优惠券面额/分（coupon/cash）；待发放时确定具体数量',
               existing_comment='奖励值；待发放时确定具体数量',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('referrals', 'reward_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_comment='pending | awarded | expired | cancelled',
               existing_nullable=False)
    op.alter_column('referrals', 'expiry_date',
               existing_type=sa.DATE(),
               comment='到期日；到期前未购课则变为 expired（Celery 每日检查）',
               existing_nullable=True)
    op.alter_column('referrals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_index('ix_referrals_referee_id', table_name='referrals')
    op.drop_index('ix_referrals_referrer_id', table_name='referrals')
    op.add_column('sessions', sa.Column('customer_package_id', sa.UUID(), nullable=False, comment='消耗的课包'))
    op.add_column('sessions', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True, comment='管理员确认时间'))
    op.add_column('sessions', sa.Column('duration_minutes', sa.Integer(), server_default='60', nullable=False, comment='服务时长（分钟）'))
    op.add_column('sessions', sa.Column('session_type', sa.String(length=100), nullable=True, comment='服务类型，如 "颈椎", "腰椎"'))
    op.add_column('sessions', sa.Column('therapist_commission_fen', sa.Integer(), nullable=True, comment='技师服务佣金（分），销课完成时计算'))
    op.add_column('sessions', sa.Column('commission_settled', sa.Boolean(), server_default='false', nullable=False, comment='佣金是否已结算'))
    op.add_column('sessions', sa.Column('clinical_notes', sa.Text(), nullable=True, comment='技师治疗笔记（内部可见）'))
    op.add_column('sessions', sa.Column('cancel_reason', sa.Text(), nullable=True, comment='取消原因'))
    op.alter_column('sessions', 'customer_id',
               existing_type=sa.UUID(),
               comment='预约客户',
               existing_nullable=False)
    op.alter_column('sessions', 'therapist_id',
               existing_type=sa.UUID(),
               comment='服务技师。Phase 1: 须等于 customer_packages.sold_by_staff_id（应用层校验）。Phase 2: 可由治疗方案独立指定（见 architecture.md § 8.4）。',
               existing_comment='服务技师；Phase 1：须等于 customer_packages.sold_by_staff_id，应用层校验。Phase 2：可与 sold_by_staff_id 不同（多技师治疗方案）。',
               existing_nullable=False)
    op.alter_column('sessions', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='客户预约时间',
               existing_comment='预约服务时间',
               existing_nullable=False)
    op.alter_column('sessions', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='实际完成时间（销课触发时记录）',
               existing_comment='实际完成时间',
               existing_nullable=True)
    op.alter_column('sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='pending | confirmed | completed | cancelled | no_show',
               existing_comment='scheduled | in_progress | completed | cancelled | no_show',
               existing_nullable=False)
    op.alter_column('sessions', 'body_areas',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment="涉及部位（PostgreSQL 数组），如 ['颈椎', '肩部']",
               existing_comment='本次服务部位标签（PostgreSQL 数组）',
               existing_nullable=True)
    op.alter_column('sessions', 'ai_session_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               nullable=False,
               comment='Phase 2: AI 诊断 / SOP 数据',
               existing_comment='AI 辅助记录（Phase 2）')
    op.drop_index('ix_sessions_customer_scheduled', table_name='sessions')
    op.drop_index('ix_sessions_package_id', table_name='sessions')
    op.create_index('ix_sessions_customer_id', 'sessions', ['customer_id'], unique=False)
    op.create_index('ix_sessions_scheduled_at', 'sessions', ['scheduled_at'], unique=False)
    op.create_index('ix_sessions_therapist_id', 'sessions', ['therapist_id'], unique=False)
    op.drop_constraint('fk_sessions_package_id', 'sessions', type_='foreignkey')
    op.drop_constraint('fk_sessions_therapist_id', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['therapist_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'sessions', 'customer_packages', ['customer_package_id'], ['id'], ondelete='RESTRICT')
    op.create_table_comment(
        'sessions',
        '预约与销课记录',
        existing_comment='服务记录（课次）',
        schema=None
    )
    op.drop_column('sessions', 'started_at')
    op.drop_column('sessions', 'package_id')
    op.drop_column('sessions', 'session_notes')
    op.alter_column('sms_codes', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='接收短信的手机号',
               existing_nullable=False)
    op.alter_column('sms_codes', 'code',
               existing_type=sa.VARCHAR(length=10),
               comment='6 位数字验证码（存储时应哈希，Phase 2 实现时注意）',
               existing_nullable=False)
    op.alter_column('sms_codes', 'is_used',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='已使用则置 TRUE，防止重放攻击',
               existing_nullable=False)
    op.alter_column('sms_codes', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='过期时间（通常为发送时间 + 5 分钟）',
               existing_nullable=False)
    op.add_column('staff_profiles', sa.Column('hire_date', sa.Date(), nullable=True))
    op.add_column('staff_profiles', sa.Column('employment_type', sa.String(length=20), nullable=True, comment='full_time | part_time'))
    op.add_column('staff_profiles', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('staff_profiles', 'user_id',
               existing_type=sa.UUID(),
               comment='关联 users.id，一个用户只能有一份技师档案',
               existing_nullable=False)
    op.alter_column('staff_profiles', 'specialty',
               existing_type=sa.VARCHAR(length=200),
               comment='专长技能，逗号分隔，如 "骶髂关节, 颈椎"',
               existing_comment='专业方向',
               existing_nullable=True)
    op.alter_column('staff_profiles', 'sales_commission_bps',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True,
               comment='销售佣金（基点，1/10000）。例：2000 = 20%',
               existing_comment='销售提成（基点，1bps=0.01%）')
    op.alter_column('staff_profiles', 'session_commission_bps',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True,
               comment='课时服务佣金（基点）。与 session_flat_rate_fen 二选一',
               existing_comment='服务提成（基点）')
    op.alter_column('staff_profiles', 'session_flat_rate_fen',
               existing_type=sa.INTEGER(),
               comment='课时固定佣金（分）。非 NULL 时优先于 session_commission_bps',
               existing_comment='服务固定提成（分）；非空时优先于 bps',
               existing_nullable=True)
    op.drop_index('ix_staff_profiles_user_id', table_name='staff_profiles')
    op.create_table_comment(
        'staff_profiles',
        '技师档案表，记录专长和佣金信息',
        existing_comment='技师 / 员工档案（1:0..1 关联 users）',
        schema=None
    )
    op.drop_column('staff_profiles', 'bio')
    op.drop_column('staff_profiles', 'employee_no')
    op.add_column('therapist_availability', sa.Column('is_available', sa.Boolean(), nullable=False, comment='TRUE=可服务；FALSE=请假/休息'))
    op.alter_column('therapist_availability', 'staff_id',
               existing_type=sa.UUID(),
               comment='关联 users.id（role=staff）',
               existing_nullable=False)
    op.alter_column('therapist_availability', 'date',
               existing_type=sa.DATE(),
               comment='当日日期（yyyy-mm-dd）',
               existing_comment='排班日期',
               existing_nullable=False)
    op.alter_column('therapist_availability', 'start_time',
               existing_type=postgresql.TIME(),
               comment='可服务开始时间（如 09:00）',
               existing_comment='时段开始时间',
               existing_nullable=False)
    op.alter_column('therapist_availability', 'end_time',
               existing_type=postgresql.TIME(),
               comment='可服务结束时间（如 18:00）',
               existing_comment='时段结束时间',
               existing_nullable=False)
    op.alter_column('therapist_availability', 'notes',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               comment='备注（如请假原因）',
               existing_nullable=True)
    op.drop_index('ix_therapist_avail_staff_date', table_name='therapist_availability')
    op.create_index(op.f('ix_therapist_availability_staff_id'), 'therapist_availability', ['staff_id'], unique=False)
    op.drop_constraint('fk_therapist_avail_staff_id', 'therapist_availability', type_='foreignkey')
    op.create_foreign_key(None, 'therapist_availability', 'users', ['staff_id'], ['id'], ondelete='CASCADE')
    op.create_table_comment(
        'therapist_availability',
        'Phase 2 预留：技师排班，Phase 1 不启用',
        existing_comment='技师排班时段（Phase 2 预留，Phase 1 不启用）',
        schema=None
    )
    op.drop_column('therapist_availability', 'slot_type')
    op.add_column('transactions', sa.Column('customer_id', sa.UUID(), nullable=False))
    op.add_column('transactions', sa.Column('customer_package_id', sa.UUID(), nullable=False))
    op.add_column('transactions', sa.Column('confirmed_by_id', sa.UUID(), nullable=True, comment='确认付款的管理员（微信支付由系统自动确认）'))
    op.add_column('transactions', sa.Column('wx_prepay_id', sa.String(length=64), nullable=True, comment='微信预支付 ID（返回给前端调起支付）'))
    op.add_column('transactions', sa.Column('bank_reference', sa.String(length=100), nullable=True, comment='银行流水参考号'))
    op.add_column('transactions', sa.Column('bank_transfer_at', sa.Date(), nullable=True, comment='银行转账日期'))
    op.add_column('transactions', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transactions', sa.Column('raw_wx_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='微信支付完整回调数据（合规存档）'))
    op.alter_column('transactions', 'amount_fen',
               existing_type=sa.INTEGER(),
               comment='正数=收款，负数=退款（分）',
               existing_comment='金额（分）；正数=收款，负数=退款',
               existing_nullable=False)
    op.alter_column('transactions', 'payment_method',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               comment='wechat_pay | bank_transfer | cash | coupon',
               existing_comment='wechat_pay | cash | bank_transfer')
    op.alter_column('transactions', 'wx_transaction_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=64),
               comment='微信支付流水号（回调中获得），幂等键',
               existing_comment='微信支付流水号（唯一）',
               existing_nullable=True)
    op.alter_column('transactions', 'wx_out_trade_no',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=64),
               comment='我方订单号（创建支付时生成）',
               existing_comment='我方支付单号（唯一，幂等键）',
               existing_nullable=True)
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='pending | confirmed | failed | cancelled',
               existing_comment='pending | success | failed | refunded',
               existing_nullable=False)
    op.drop_index('ix_transactions_package_id', table_name='transactions')
    op.drop_index('ix_transactions_user_id', table_name='transactions')
    op.create_index('ix_transactions_customer_id', 'transactions', ['customer_id'], unique=False)
    op.drop_constraint('fk_transactions_user_id', 'transactions', type_='foreignkey')
    op.drop_constraint('fk_transactions_package_id', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'customer_packages', ['customer_package_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'transactions', 'users', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'transactions', 'users', ['confirmed_by_id'], ['id'], ondelete='SET NULL')
    op.create_table_comment(
        'transactions',
        '交易/付款记录（永久保留，无软删除）',
        existing_comment='资金流水（无软删除，财务记录永久保留）',
        schema=None
    )
    op.drop_column('transactions', 'tx_type')
    op.drop_column('transactions', 'user_id')
    op.drop_column('transactions', 'package_id')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_comment='customer | staff | admin',
               existing_nullable=False)
    op.alter_column('users', 'openid',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=64),
               comment='微信小程序 openid，同一小程序内唯一',
               existing_comment='微信小程序 openid',
               existing_nullable=True)
    op.alter_column('users', 'unionid',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=64),
               comment='微信开放平台 UnionID，跨端账号合并的关键字段。仅当小程序已绑定微信开放平台主体时才有值（见 architecture.md § 8.2）。',
               existing_comment='微信开放平台 unionid（跨平台账号合并关键字段）',
               existing_nullable=True)
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               comment='前端展示名称（优先取 real_name，其次 wechat_nickname）',
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(length=500),
               comment='头像 URL',
               existing_nullable=True)
    op.alter_column('users', 'referral_code',
               existing_type=sa.VARCHAR(length=20),
               comment='用户专属邀请码（用于转介绍）',
               existing_comment='用户专属邀请码',
               existing_nullable=True)
    op.alter_column('users', 'wechat_phone',
               existing_type=sa.VARCHAR(length=20),
               comment='通过 wx.getPhoneNumber 获取的手机号',
               existing_comment='wx.getPhoneNumber 获取',
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='绑定手机号，Web 端登录凭据（Phase 2）',
               existing_comment='绑定手机号',
               existing_nullable=True)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_comment='male | female | unknown',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'ai_profile',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Phase 2: AI 诊断画像（初始为空 JSON）',
               existing_comment='AI 诊断画像（Phase 2）',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('users', 'first_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='首次登录时间（用于统计新用户）',
               existing_nullable=True)
    op.drop_index('ix_users_phone', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.create_table_comment(
        'users',
        '系统所有角色的用户表（客户 / 技师 / 管理员）',
        existing_comment='用户（客户 / 技师 / 管理员）',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        '用户（客户 / 技师 / 管理员）',
        existing_comment='系统所有角色的用户表（客户 / 技师 / 管理员）',
        schema=None
    )
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.alter_column('users', 'first_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='首次登录时间（用于统计新用户）',
               existing_nullable=True)
    op.alter_column('users', 'ai_profile',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='AI 诊断画像（Phase 2）',
               existing_comment='Phase 2: AI 诊断画像（初始为空 JSON）',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'unknown'::character varying"),
               existing_comment='male | female | unknown',
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='绑定手机号',
               existing_comment='绑定手机号，Web 端登录凭据（Phase 2）',
               existing_nullable=True)
    op.alter_column('users', 'wechat_phone',
               existing_type=sa.VARCHAR(length=20),
               comment='wx.getPhoneNumber 获取',
               existing_comment='通过 wx.getPhoneNumber 获取的手机号',
               existing_nullable=True)
    op.alter_column('users', 'referral_code',
               existing_type=sa.VARCHAR(length=20),
               comment='用户专属邀请码',
               existing_comment='用户专属邀请码（用于转介绍）',
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='头像 URL',
               existing_nullable=True)
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='前端展示名称（优先取 real_name，其次 wechat_nickname）',
               existing_nullable=True)
    op.alter_column('users', 'unionid',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=100),
               comment='微信开放平台 unionid（跨平台账号合并关键字段）',
               existing_comment='微信开放平台 UnionID，跨端账号合并的关键字段。仅当小程序已绑定微信开放平台主体时才有值（见 architecture.md § 8.2）。',
               existing_nullable=True)
    op.alter_column('users', 'openid',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=100),
               comment='微信小程序 openid',
               existing_comment='微信小程序 openid，同一小程序内唯一',
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'customer'::character varying"),
               existing_comment='customer | staff | admin',
               existing_nullable=False)
    op.add_column('transactions', sa.Column('package_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('tx_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False, comment='purchase | refund | gift | adjustment'))
    op.create_table_comment(
        'transactions',
        '资金流水（无软删除，财务记录永久保留）',
        existing_comment='交易/付款记录（永久保留，无软删除）',
        schema=None
    )
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('fk_transactions_package_id', 'transactions', 'customer_packages', ['package_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_transactions_user_id', 'transactions', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.drop_index('ix_transactions_customer_id', table_name='transactions')
    op.create_index('ix_transactions_user_id', 'transactions', ['user_id'], unique=False)
    op.create_index('ix_transactions_package_id', 'transactions', ['package_id'], unique=False)
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               comment='pending | success | failed | refunded',
               existing_comment='pending | confirmed | failed | cancelled',
               existing_nullable=False)
    op.alter_column('transactions', 'wx_out_trade_no',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=100),
               comment='我方支付单号（唯一，幂等键）',
               existing_comment='我方订单号（创建支付时生成）',
               existing_nullable=True)
    op.alter_column('transactions', 'wx_transaction_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=100),
               comment='微信支付流水号（唯一）',
               existing_comment='微信支付流水号（回调中获得），幂等键',
               existing_nullable=True)
    op.alter_column('transactions', 'payment_method',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               comment='wechat_pay | cash | bank_transfer',
               existing_comment='wechat_pay | bank_transfer | cash | coupon')
    op.alter_column('transactions', 'amount_fen',
               existing_type=sa.INTEGER(),
               comment='金额（分）；正数=收款，负数=退款',
               existing_comment='正数=收款，负数=退款（分）',
               existing_nullable=False)
    op.drop_column('transactions', 'raw_wx_response')
    op.drop_column('transactions', 'confirmed_at')
    op.drop_column('transactions', 'bank_transfer_at')
    op.drop_column('transactions', 'bank_reference')
    op.drop_column('transactions', 'wx_prepay_id')
    op.drop_column('transactions', 'confirmed_by_id')
    op.drop_column('transactions', 'customer_package_id')
    op.drop_column('transactions', 'customer_id')
    op.add_column('therapist_availability', sa.Column('slot_type', sa.VARCHAR(length=20), server_default=sa.text("'available'::character varying"), autoincrement=False, nullable=False, comment='available | blocked | booked'))
    op.create_table_comment(
        'therapist_availability',
        '技师排班时段（Phase 2 预留，Phase 1 不启用）',
        existing_comment='Phase 2 预留：技师排班，Phase 1 不启用',
        schema=None
    )
    op.drop_constraint(None, 'therapist_availability', type_='foreignkey')
    op.create_foreign_key('fk_therapist_avail_staff_id', 'therapist_availability', 'staff_profiles', ['staff_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_therapist_availability_staff_id'), table_name='therapist_availability')
    op.create_index('ix_therapist_avail_staff_date', 'therapist_availability', ['staff_id', 'date'], unique=False)
    op.alter_column('therapist_availability', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='备注（如请假原因）',
               existing_nullable=True)
    op.alter_column('therapist_availability', 'end_time',
               existing_type=postgresql.TIME(),
               comment='时段结束时间',
               existing_comment='可服务结束时间（如 18:00）',
               existing_nullable=False)
    op.alter_column('therapist_availability', 'start_time',
               existing_type=postgresql.TIME(),
               comment='时段开始时间',
               existing_comment='可服务开始时间（如 09:00）',
               existing_nullable=False)
    op.alter_column('therapist_availability', 'date',
               existing_type=sa.DATE(),
               comment='排班日期',
               existing_comment='当日日期（yyyy-mm-dd）',
               existing_nullable=False)
    op.alter_column('therapist_availability', 'staff_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='关联 users.id（role=staff）',
               existing_nullable=False)
    op.drop_column('therapist_availability', 'is_available')
    op.add_column('staff_profiles', sa.Column('employee_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='工号'))
    op.add_column('staff_profiles', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True, comment='简介'))
    op.create_table_comment(
        'staff_profiles',
        '技师 / 员工档案（1:0..1 关联 users）',
        existing_comment='技师档案表，记录专长和佣金信息',
        schema=None
    )
    op.create_index('ix_staff_profiles_user_id', 'staff_profiles', ['user_id'], unique=False)
    op.alter_column('staff_profiles', 'session_flat_rate_fen',
               existing_type=sa.INTEGER(),
               comment='服务固定提成（分）；非空时优先于 bps',
               existing_comment='课时固定佣金（分）。非 NULL 时优先于 session_commission_bps',
               existing_nullable=True)
    op.alter_column('staff_profiles', 'session_commission_bps',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False,
               comment='服务提成（基点）',
               existing_comment='课时服务佣金（基点）。与 session_flat_rate_fen 二选一')
    op.alter_column('staff_profiles', 'sales_commission_bps',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False,
               comment='销售提成（基点，1bps=0.01%）',
               existing_comment='销售佣金（基点，1/10000）。例：2000 = 20%')
    op.alter_column('staff_profiles', 'specialty',
               existing_type=sa.VARCHAR(length=200),
               comment='专业方向',
               existing_comment='专长技能，逗号分隔，如 "骶髂关节, 颈椎"',
               existing_nullable=True)
    op.alter_column('staff_profiles', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='关联 users.id，一个用户只能有一份技师档案',
               existing_nullable=False)
    op.drop_column('staff_profiles', 'notes')
    op.drop_column('staff_profiles', 'employment_type')
    op.drop_column('staff_profiles', 'hire_date')
    op.alter_column('sms_codes', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='过期时间（通常为发送时间 + 5 分钟）',
               existing_nullable=False)
    op.alter_column('sms_codes', 'is_used',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='已使用则置 TRUE，防止重放攻击',
               existing_nullable=False)
    op.alter_column('sms_codes', 'code',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='6 位数字验证码（存储时应哈希，Phase 2 实现时注意）',
               existing_nullable=False)
    op.alter_column('sms_codes', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='接收短信的手机号',
               existing_nullable=False)
    op.add_column('sessions', sa.Column('session_notes', sa.TEXT(), autoincrement=False, nullable=True, comment='治疗师本次记录'))
    op.add_column('sessions', sa.Column('package_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('sessions', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='实际开始时间'))
    op.create_table_comment(
        'sessions',
        '服务记录（课次）',
        existing_comment='预约与销课记录',
        schema=None
    )
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('fk_sessions_therapist_id', 'sessions', 'staff_profiles', ['therapist_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_sessions_package_id', 'sessions', 'customer_packages', ['package_id'], ['id'], ondelete='RESTRICT')
    op.drop_index('ix_sessions_therapist_id', table_name='sessions')
    op.drop_index('ix_sessions_scheduled_at', table_name='sessions')
    op.drop_index('ix_sessions_customer_id', table_name='sessions')
    op.create_index('ix_sessions_package_id', 'sessions', ['package_id'], unique=False)
    op.create_index('ix_sessions_customer_scheduled', 'sessions', ['customer_id', 'scheduled_at'], unique=False)
    op.alter_column('sessions', 'ai_session_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=True,
               comment='AI 辅助记录（Phase 2）',
               existing_comment='Phase 2: AI 诊断 / SOP 数据')
    op.alter_column('sessions', 'body_areas',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment='本次服务部位标签（PostgreSQL 数组）',
               existing_comment="涉及部位（PostgreSQL 数组），如 ['颈椎', '肩部']",
               existing_nullable=True)
    op.alter_column('sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'scheduled'::character varying"),
               comment='scheduled | in_progress | completed | cancelled | no_show',
               existing_comment='pending | confirmed | completed | cancelled | no_show',
               existing_nullable=False)
    op.alter_column('sessions', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='实际完成时间',
               existing_comment='实际完成时间（销课触发时记录）',
               existing_nullable=True)
    op.alter_column('sessions', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='预约服务时间',
               existing_comment='客户预约时间',
               existing_nullable=False)
    op.alter_column('sessions', 'therapist_id',
               existing_type=sa.UUID(),
               comment='服务技师；Phase 1：须等于 customer_packages.sold_by_staff_id，应用层校验。Phase 2：可与 sold_by_staff_id 不同（多技师治疗方案）。',
               existing_comment='服务技师。Phase 1: 须等于 customer_packages.sold_by_staff_id（应用层校验）。Phase 2: 可由治疗方案独立指定（见 architecture.md § 8.4）。',
               existing_nullable=False)
    op.alter_column('sessions', 'customer_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='预约客户',
               existing_nullable=False)
    op.drop_column('sessions', 'cancel_reason')
    op.drop_column('sessions', 'clinical_notes')
    op.drop_column('sessions', 'commission_settled')
    op.drop_column('sessions', 'therapist_commission_fen')
    op.drop_column('sessions', 'session_type')
    op.drop_column('sessions', 'duration_minutes')
    op.drop_column('sessions', 'confirmed_at')
    op.drop_column('sessions', 'customer_package_id')
    op.create_index('ix_referrals_referrer_id', 'referrals', ['referrer_id'], unique=False)
    op.create_index('ix_referrals_referee_id', 'referrals', ['referee_id'], unique=False)
    op.alter_column('referrals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('referrals', 'expiry_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='到期日；到期前未购课则变为 expired（Celery 每日检查）',
               existing_nullable=True)
    op.alter_column('referrals', 'reward_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_comment='pending | awarded | expired | cancelled',
               existing_nullable=False)
    op.alter_column('referrals', 'reward_value',
               existing_type=sa.INTEGER(),
               comment='奖励值；待发放时确定具体数量',
               existing_comment='奖励值：课时数（gift_session）或优惠券面额/分（coupon/cash）；待发放时确定具体数量',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('referrals', 'reward_type',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'gift_session'::character varying"),
               existing_comment='gift_session | coupon | cash',
               existing_nullable=False)
    op.alter_column('referrals', 'referee_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='被推荐人（新客户），每人只能被推荐一次',
               existing_nullable=False)
    op.alter_column('referrals', 'referrer_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='推荐人（老客户）',
               existing_nullable=False)
    op.alter_column('notification_logs', 'trigger_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='manual_blast | session_reminder | package_expiry | referral_reward | promotion',
               existing_nullable=False)
    op.alter_column('notification_logs', 'wx_msg_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='微信返回的消息 ID',
               existing_nullable=True)
    op.alter_column('notification_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_comment='pending | sent | failed',
               existing_nullable=False)
    op.alter_column('notification_logs', 'content_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='发送时的完整消息体快照（审计留存）',
               existing_nullable=False)
    op.alter_column('notification_logs', 'channel',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'subscribe_message'::character varying"),
               comment=None,
               existing_comment='subscribe_message | sms（Phase 2）| email（Phase 2）',
               existing_nullable=False)
    op.alter_column('notification_logs', 'template_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='微信订阅消息模板 ID',
               existing_nullable=False)
    op.alter_column('notification_logs', 'triggered_by_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='触发此通知的管理员；NULL = 系统自动触发',
               existing_nullable=True)
    op.add_column('customer_packages', sa.Column('coupon_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('customer_packages', sa.Column('price_paid_fen', sa.INTEGER(), autoincrement=False, nullable=False, comment='实际支付金额（分）'))
    op.create_table_comment(
        'customer_packages',
        '客户课包（购买记录）',
        existing_comment='客户课包，追踪购买和课时消耗',
        schema=None
    )
    op.drop_constraint(None, 'customer_packages', type_='foreignkey')
    op.drop_constraint(None, 'customer_packages', type_='foreignkey')
    op.create_foreign_key('fk_customer_packages_sold_by_staff_id', 'customer_packages', 'staff_profiles', ['sold_by_staff_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_customer_packages_coupon_id', 'customer_packages', 'coupons', ['coupon_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_customer_packages_expiry', table_name='customer_packages')
    op.create_index('ix_customer_packages_expiry', 'customer_packages', ['expiry_date', 'payment_status'], unique=False)
    op.alter_column('customer_packages', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               comment='pending | paid | refunded | partial_refunded',
               existing_comment='pending | partial | paid | refunded',
               existing_nullable=False)
    op.alter_column('customer_packages', 'sessions_gifted',
               existing_type=sa.INTEGER(),
               comment='赠送课次数',
               existing_comment='转介绍奖励赠送课时',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('customer_packages', 'sessions_used',
               existing_type=sa.INTEGER(),
               comment='已完成课次数（行锁保护，防并发错误）',
               existing_comment='已消耗课时（每次销课 +1，受 CHECK 约束）',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('customer_packages', 'sessions_total',
               existing_type=sa.INTEGER(),
               comment='购买课次数',
               existing_comment='总课时数（从 Course.session_count 复制）',
               existing_nullable=False)
    op.alter_column('customer_packages', 'expiry_date',
               existing_type=sa.DATE(),
               comment='到期日；NULL 永不过期',
               existing_comment='到期日期（由 validity_days 计算）；NULL = 不限期',
               existing_nullable=True)
    op.alter_column('customer_packages', 'sold_by_staff_id',
               existing_type=sa.UUID(),
               comment='销售技师；Phase 1：therapist_id 必须等于此值（应用层校验）',
               existing_comment='销售该课包的技师。Phase 1: 同时决定服务技师（SessionRecord.therapist_id 须等于此值）。Phase 2: 独立于治疗方案指定的技师。',
               existing_nullable=True)
    op.alter_column('customer_packages', 'course_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='购买的课程模板',
               existing_nullable=False)
    op.alter_column('customer_packages', 'customer_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='购买客户',
               existing_nullable=False)
    op.drop_column('customer_packages', 'sold_by_commission_fen')
    op.drop_column('customer_packages', 'amount_paid_fen')
    op.drop_column('customer_packages', 'agreed_price_fen')
    op.drop_column('customer_packages', 'purchase_date')
    op.drop_column('customer_packages', 'referral_id')
    op.add_column('courses', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='课程分类'))
    op.add_column('courses', sa.Column('sessions_included', sa.INTEGER(), autoincrement=False, nullable=False, comment='标准课次数'))
    op.create_table_comment(
        'courses',
        '课程 / 服务项目定义',
        existing_comment='课程目录，定义套餐/单次课的规格和价格',
        schema=None
    )
    op.create_index('ix_courses_is_active', 'courses', ['is_active'], unique=False)
    op.create_index('ix_courses_category', 'courses', ['category'], unique=False)
    op.alter_column('courses', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=True,
               comment='扩展属性（Phase 2）',
               existing_comment='扩展元数据（JSON）')
    op.alter_column('courses', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment='FALSE 时不在前端展示',
               existing_comment='FALSE = 下架；客户端不展示，但已购课包不受影响',
               existing_nullable=False)
    op.alter_column('courses', 'price_fen',
               existing_type=sa.INTEGER(),
               comment='标准售价（分）',
               existing_comment='定价（分）',
               existing_nullable=False)
    op.alter_column('courses', 'validity_days',
               existing_type=sa.INTEGER(),
               comment='有效期（天）；NULL 表示永不过期',
               existing_comment='有效天数；NULL 表示不限期',
               existing_nullable=True)
    op.alter_column('courses', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='课程名称',
               existing_comment='课程名称，如 "肩颈调理套餐 10次"',
               existing_nullable=False)
    op.drop_column('courses', 'sop_template_id')
    op.drop_column('courses', 'promo_end_at')
    op.drop_column('courses', 'promo_start_at')
    op.drop_column('courses', 'promo_price_fen')
    op.drop_column('courses', 'cost_per_session_fen')
    op.drop_column('courses', 'session_count')
    op.drop_column('courses', 'course_type')
    op.add_column('coupons', sa.Column('min_order_fen', sa.INTEGER(), autoincrement=False, nullable=True, comment='最低消费金额（分）'))
    op.add_column('coupons', sa.Column('usage_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='已使用次数'))
    op.add_column('coupons', sa.Column('usage_limit', sa.INTEGER(), autoincrement=False, nullable=True, comment='最大使用次数；NULL 表示不限'))
    op.add_column('coupons', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('coupons', sa.Column('max_discount_fen', sa.INTEGER(), autoincrement=False, nullable=True, comment='最大抵扣金额（分）'))
    op.create_table_comment(
        'coupons',
        '优惠券',
        existing_comment='优惠券，支持转介绍奖励和手动发放',
        schema=None
    )
    op.drop_constraint(None, 'coupons', type_='foreignkey')
    op.drop_constraint(None, 'coupons', type_='foreignkey')
    op.drop_constraint(None, 'coupons', type_='foreignkey')
    op.create_index('ix_coupons_code', 'coupons', ['code'], unique=False)
    op.alter_column('coupons', 'discount_value',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='折扣值（配合 discount_type 解读）',
               existing_nullable=False)
    op.alter_column('coupons', 'discount_type',
               existing_type=sa.VARCHAR(length=20),
               comment='fixed_fen | percentage_bps',
               existing_comment='fixed_fen（固定减免分）| percentage_bps（百分比基点）',
               existing_nullable=False)
    op.alter_column('coupons', 'code',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               comment='优惠券码（唯一）',
               existing_comment='优惠券唯一码，如 "REF-ABCD"',
               existing_nullable=False)
    op.drop_column('coupons', 'used_on_package_id')
    op.drop_column('coupons', 'used_at')
    op.drop_column('coupons', 'is_used')
    op.drop_column('coupons', 'min_purchase_fen')
    op.drop_column('coupons', 'referral_id')
    op.drop_column('coupons', 'customer_id')
    # ### end Alembic commands ###
